apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.container.name }}-service
spec:
  ports:
    - port: {{ .Values.container.port }}
      protocol: TCP
      targetPort: {{ .Values.container.port }}
  selector:
    app: {{ .Values.container.name }}
  sessionAffinity: None
  type: ClusterIP